vim.cmd("let g:netrw_liststyle = 3")    -- netrw is the built in nvim file explorer. The style is set to tree-style

local opt=vim.opt

opt.clipboard = "unnamedplus"   -- access to clipboard
opt.modifiable = true
-- opt.cmdheight = 2               -- command line height
opt.completeopt = { "menuone", "noselect" }     -- completion commands
opt.fileencoding = "utf-8"
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.termguicolors = true
opt.ignorecase = true
opt.wrap = false
opt.cursorline = true
opt.cursorcolumn = true
opt.laststatus = 2
opt.backspace = eol,indent,start
opt.ruler = true
opt.number = true
opt.relativenumber = true
opt.shiftwidth = 4
opt.tabstop = 4
opt.expandtab = true
opt.smarttab = true
opt.backup = false
opt.smartindent = true
opt.smartcase = true
opt.incsearch = true
opt.showcmd = true
opt.showmode = true
opt.showmatch = true
opt.hlsearch = true
opt.background = "dark"
opt.signcolumn = "yes"
opt.mat = 2
opt.autoindent = true
opt.smartindent = true
opt.updatetime = 100
